name: vitepress-build-deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci
      - name: Build
        run: npm run docs:build
      - name: Upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/.vitepress/dist
